### ISSUE TITLE
Modal not defined on refresh

### ISSUE THREAD

**Issue by valdimarHR** [Greentube/ngx-modal#3]
I'm getting an error when refreshing on components that have ngx_modals in them or the first page that I request has a modal. It works fine if I don't refresh and the first page has no modal. I have imported them in the component and app.module. Im not using a system.js file and Im new to webpack. Here is what I get when I refresh (or the first page that is run has a modal):

**An unhandled exception occurred while processing the request.**
Exception: Call to Node module failed with error: Error: Uncaught (in promise): ReferenceError: document is not defined
ReferenceError: document is not defined
at Modal.createBackDrop (C:\Whatever\Server\ClientApp\dist\main-server.js:4043:32)
at new Modal (C:\Whateve\Server\ClientApp\dist\main-server.js:3997:14)
at new Wrapper_Modal (/ModalModule/Modal/wrapper.ngfactory.js:6:18)

Thanks

**Comment by joaopgrassi** [comment]
Hi @valdimarHR 
Is it possible for you to create a reproducible repo of the issue? This way we can investigate further.

**Comment by meeroslav** [comment]
Hi @valdimarHR

The error log you provided doesn't seem to be coming from `ngx-modal-dialog`. Our code does not have `createBackDrop` method nor `Modal` class. Are you maybe using some other modal dialogs in your code that is causing this?

**Comment by meeroslav** [comment]
Closing due to inactivity of the OP
